spring.datasource.url=jdbc:mysql://localhost:3306/finance_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Laksh440
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.jwt.secret=financedashboard2024supersecretkey256bits
app.jwt.expiration=86400000

server.port=8080
